id: I98877D5D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:59:53+00:00'
last_modified: '2022-06-08T12:55:45.100751+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4341
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3761':
      image_group_id: I3CN4576
      title: Volume 1 of snying thig sngon 'gro'i zin bris/
      total_pages: 274
      order: 1
      base_file: 3761.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
