id: P006955
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4341
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  author: ''
  volumes:
    73da9be6e9874ba0b6257bb82bc06c40:
      image_group_id: I3CN4576
      title: ''
      volume_number: 1
      total_pages: 274
ebook_metadata:
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  author: ''
  sku: P006955
  cover: cover.jpg
  layers:
  - pagination
