id: P006955
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4341
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  author: ''
  volumes:
    f02aa76c2af344eeb4091a54fefbd638:
      image_group_id: I3CN4576
      title: Volume 1 of snying thig sngon 'gro'i zin bris/
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
