id: opecha:P006955
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4341
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  volume:
    f02aa76c2af344eeb4091a54fefbd638:
      image_group_id: I3CN4576
      title: Volume 1 of snying thig sngon 'gro'i zin bris/
      volume_number: 1
      total_pages: 274
  author: ''
ebook_metadata:
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཟིན་བྲིས།
  author: ''
  sku: P006955
  cover: cover.jpg
  layers:
  - pagination
